# Generated by Django 5.2.4 on 2025-11-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="meal_plan",
            field=models.CharField(
                choices=[
                    ("HB", "Half Board (Breakfast + One Meal)"),
                    ("FB", "Full Board (Breakfast, Lunch & Dinner)"),
                ],
                default="HB",
                max_length=2,
            ),
        ),
    ]
