# Generated by Django 5.2.4 on 2025-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_booking_adults_booking_children_booking_meal_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
