# Generated by Django 5.2.4 on 2025-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_booking_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="mpesa_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
